import { describe, expect, it } from "vitest";

import { recordPhase7LocalCommandEvidence } from "../src/phase7CommandRecorder.js";

describe("Phase 7 command recorder", () => {
  it("records safe local command transcript blocks", () => {
    const writes: Array<{ path: string; text: string }> = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "evidence/commands.log",
      exists: () => false,
      now: () => new Date("2026-07-04T00:00:00.000Z"),
      writeText: (path, text) => writes.push({ path, text }),
      runCommand: (file, args) => ({
        exitCode: 0,
        stdout: `${file} ${args.join(" ")} ok\n`,
        stderr: "",
      }),
    });

    expect(report).toMatchObject({
      ok: true,
      outputPath: "evidence/commands.log",
      commandCount: 10,
      failedCommands: [],
      written: true,
    });
    expect(writes).toHaveLength(1);
    expect(writes[0]?.text).toContain(
      "# Generated by corepack pnpm phase7:staging:commands-record.",
    );
    expect(writes[0]?.text).toContain("$ git rev-parse HEAD");
    expect(writes[0]?.text).toContain("$ corepack pnpm lint");
    expect(writes[0]?.text).toContain(
      "$ corepack pnpm audit --audit-level high",
    );
    expect(writes[0]?.text).not.toContain("phase7:docker:health");
    expect(report.nextActions).toContain(
      "Append any missing hosted Docker, seed, collection, paid-suite, manifest, assemble, and status command outputs to evidence/commands.log.",
    );
  });

  it("can record the full hosted staging command checklist", () => {
    const writes: Array<{ path: string; text: string }> = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "evidence/commands.log",
      includeHosted: true,
      evidenceEnvFile: "private/phase7.env",
      evidenceDirectory: "private/evidence",
      proofPath: "private/phase7-proof.txt",
      seedOutputPath: "private/phase7-seed.json",
      exists: () => false,
      writeText: (path, text) => writes.push({ path, text }),
      runCommand: (file, args) => ({
        exitCode: 0,
        stdout: `${file} ${args.join(" ")} ok\n`,
        stderr: "",
      }),
    });

    expect(report).toMatchObject({
      ok: true,
      commandCount: 28,
      failedCommands: [],
      written: true,
    });
    const transcript = writes.find((write) => write.path === "evidence/commands.log");
    const seedOutput = writes.find((write) => write.path === "private/phase7-seed.json");
    expect(transcript?.text).toContain(
      "# This includes hosted staging commands from this runtime.",
    );
    expect(transcript?.text).toContain("$ corepack pnpm product:evidence:init --missing");
    expect(transcript?.text).toContain(
      "$ corepack pnpm phase7:docker:compose up --brief --profile demo --profile workers",
    );
    expect(transcript?.text).toContain("$ corepack pnpm phase7:staging:seed");
    expect(transcript?.text).toContain(
      "$ corepack pnpm phase7:staging:apply-seed-env --seed-output private/phase7-seed.json",
    );
    expect(transcript?.text).toContain("$ corepack pnpm phase7:staging:status");
    expect(transcript?.text).toContain("private/phase7.env");
    expect(transcript?.text).toContain("private/evidence/paid-suite.log");
    expect(transcript?.text).toContain("private/phase7-proof.txt");
    expect(transcript?.text).toContain("$ corepack pnpm audit --audit-level high");
    expect(seedOutput?.text).toBe("corepack pnpm phase7:staging:seed ok\n");
    expect(
      transcript?.text.indexOf("$ corepack pnpm demo:paid-suite") ?? -1,
    ).toBeLessThan(
      transcript?.text.indexOf("$ corepack pnpm phase7:staging:collect-reads") ??
        -1,
    );
  });

  it("redacts sensitive command output before writing transcripts", () => {
    const writes: Array<{ path: string; text: string }> = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "evidence/commands.log",
      includeHosted: true,
      exists: () => false,
      writeText: (path, text) => writes.push({ path, text }),
      runCommand: (_file, args) =>
        args.includes("phase7:staging:seed")
          ? {
              exitCode: 0,
              stdout: [
                '{"proofEnv":{"SPLIT402_PHASE7_CONTROL_PLANE_TOKEN":"super-secret-token","SVM_PRIVATE_KEY":"private-key","SPLIT402_SERVICE_SEED_HEX":"seed-value"}}',
                "SPLIT402_WEBHOOK_WORKER_SECRET=webhook-secret",
                "",
              ].join("\n"),
              stderr: "SPLIT402_PHASE7_CONTROL_PLANE_TOKEN=stderr-secret\n",
            }
          : { exitCode: 0, stdout: "ok\n", stderr: "" },
    });

    const transcript = writes.find((write) => write.path === "evidence/commands.log");
    const seedOutput = writes.find(
      (write) => write.path === "split402-launch-evidence/phase7-seed.json",
    );
    expect(report.ok).toBe(true);
    expect(transcript?.text).toContain(
      '"SPLIT402_PHASE7_CONTROL_PLANE_TOKEN":"[redacted]"',
    );
    expect(transcript?.text).toContain('"SVM_PRIVATE_KEY":"[redacted]"');
    expect(transcript?.text).toContain('"SPLIT402_SERVICE_SEED_HEX":"[redacted]"');
    expect(transcript?.text).toContain(
      "SPLIT402_WEBHOOK_WORKER_SECRET=[redacted]",
    );
    expect(transcript?.text).not.toContain("super-secret-token");
    expect(transcript?.text).not.toContain("private-key");
    expect(transcript?.text).not.toContain("seed-value");
    expect(transcript?.text).not.toContain("webhook-secret");
    expect(transcript?.text).not.toContain("stderr-secret");
    expect(seedOutput?.text).toContain("super-secret-token");
  });

  it("can include launch preflight when the operator opts in", () => {
    const writes: string[] = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "commands.log",
      includePreflight: true,
      exists: () => false,
      writeText: (_path, text) => writes.push(text),
      runCommand: () => ({ exitCode: 0, stdout: "ok\n", stderr: "" }),
    });

    expect(report.commandCount).toBe(11);
    expect(writes[0]).toContain(
      "$ corepack pnpm product:launch-preflight --brief --workspace split402-launch-evidence",
    );
  });

  it("refuses to overwrite an existing transcript unless forced", () => {
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "commands.log",
      exists: () => true,
      writeText: () => {
        throw new Error("should not write");
      },
      runCommand: () => {
        throw new Error("should not run");
      },
    });

    expect(report.ok).toBe(false);
    expect(report.written).toBe(false);
    expect(report.nextActions).toContain(
      "Refusing to overwrite commands.log; pass --force only after saving any real hosted transcript content.",
    );
  });

  it("records failing commands and marks the report blocked", () => {
    let commandIndex = 0;
    const writes: string[] = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "commands.log",
      force: true,
      exists: () => true,
      writeText: (_path, text) => writes.push(text),
      runCommand: () => {
        commandIndex += 1;
        return commandIndex === 4
          ? { exitCode: 1, stdout: "", stderr: "lint failed\n" }
          : { exitCode: 0, stdout: "ok\n", stderr: "" };
      },
    });

    expect(report.ok).toBe(false);
    expect(report.failedCommands).toEqual(["corepack pnpm lint"]);
    expect(writes[0]).toContain("$ corepack pnpm lint\nlint failed\n# exit_code: 1");
    expect(report.nextActions).toContain(
      "Fix failed local commands: corepack pnpm lint.",
    );
  });
});
