import { describe, expect, it } from "vitest";

import { recordPhase7LocalCommandEvidence } from "../src/phase7CommandRecorder.js";

describe("Phase 7 command recorder", () => {
  it("records safe local command transcript blocks", () => {
    const writes: Array<{ path: string; text: string }> = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "evidence/commands.log",
      exists: () => false,
      now: () => new Date("2026-07-04T00:00:00.000Z"),
      writeText: (path, text) => writes.push({ path, text }),
      runCommand: (file, args) => ({
        exitCode: 0,
        stdout: `${file} ${args.join(" ")} ok\n`,
        stderr: "",
      }),
    });

    expect(report).toMatchObject({
      ok: true,
      outputPath: "evidence/commands.log",
      commandCount: 10,
      failedCommands: [],
      written: true,
    });
    expect(writes).toHaveLength(1);
    expect(writes[0]?.text).toContain(
      "# Generated by corepack pnpm phase7:staging:commands-record.",
    );
    expect(writes[0]?.text).toContain("$ git rev-parse HEAD");
    expect(writes[0]?.text).toContain("$ corepack pnpm lint");
    expect(writes[0]?.text).toContain(
      "$ corepack pnpm audit --audit-level high",
    );
    expect(writes[0]?.text).not.toContain("phase7:docker:health");
    expect(report.nextActions).toContain(
      "Append any missing hosted Docker, seed, collection, paid-suite, manifest, assemble, and status command outputs to evidence/commands.log.",
    );
  });

  it("can record the full hosted staging command checklist", () => {
    const writes: string[] = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "evidence/commands.log",
      includeHosted: true,
      evidenceEnvFile: "private/phase7.env",
      evidenceDirectory: "private/evidence",
      proofPath: "private/phase7-proof.txt",
      exists: () => false,
      writeText: (_path, text) => writes.push(text),
      runCommand: (file, args) => ({
        exitCode: 0,
        stdout: `${file} ${args.join(" ")} ok\n`,
        stderr: "",
      }),
    });

    expect(report).toMatchObject({
      ok: true,
      commandCount: 27,
      failedCommands: [],
      written: true,
    });
    expect(writes[0]).toContain(
      "# This includes hosted staging commands from this runtime.",
    );
    expect(writes[0]).toContain("$ corepack pnpm product:evidence:init --missing");
    expect(writes[0]).toContain(
      "$ corepack pnpm phase7:docker:compose up --brief --profile demo --profile workers",
    );
    expect(writes[0]).toContain("$ corepack pnpm phase7:staging:seed");
    expect(writes[0]).toContain("$ corepack pnpm phase7:staging:status");
    expect(writes[0]).toContain("private/phase7.env");
    expect(writes[0]).toContain("private/evidence/paid-suite.log");
    expect(writes[0]).toContain("private/phase7-proof.txt");
    expect(writes[0]).toContain("$ corepack pnpm audit --audit-level high");
  });

  it("can include launch preflight when the operator opts in", () => {
    const writes: string[] = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "commands.log",
      includePreflight: true,
      exists: () => false,
      writeText: (_path, text) => writes.push(text),
      runCommand: () => ({ exitCode: 0, stdout: "ok\n", stderr: "" }),
    });

    expect(report.commandCount).toBe(11);
    expect(writes[0]).toContain(
      "$ corepack pnpm product:launch-preflight --brief --workspace split402-launch-evidence",
    );
  });

  it("refuses to overwrite an existing transcript unless forced", () => {
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "commands.log",
      exists: () => true,
      writeText: () => {
        throw new Error("should not write");
      },
      runCommand: () => {
        throw new Error("should not run");
      },
    });

    expect(report.ok).toBe(false);
    expect(report.written).toBe(false);
    expect(report.nextActions).toContain(
      "Refusing to overwrite commands.log; pass --force only after saving any real hosted transcript content.",
    );
  });

  it("records failing commands and marks the report blocked", () => {
    let commandIndex = 0;
    const writes: string[] = [];
    const report = recordPhase7LocalCommandEvidence({
      outputPath: "commands.log",
      force: true,
      exists: () => true,
      writeText: (_path, text) => writes.push(text),
      runCommand: () => {
        commandIndex += 1;
        return commandIndex === 4
          ? { exitCode: 1, stdout: "", stderr: "lint failed\n" }
          : { exitCode: 0, stdout: "ok\n", stderr: "" };
      },
    });

    expect(report.ok).toBe(false);
    expect(report.failedCommands).toEqual(["corepack pnpm lint"]);
    expect(writes[0]).toContain("$ corepack pnpm lint\nlint failed\n# exit_code: 1");
    expect(report.nextActions).toContain(
      "Fix failed local commands: corepack pnpm lint.",
    );
  });
});
