export interface Phase7CommandRecorderInput {
  outputPath: string;
  force?: boolean;
  includePreflight?: boolean;
  exists: (path: string) => boolean;
  runCommand: (
    file: string,
    args: readonly string[],
  ) => Phase7RecordedCommandResult;
  writeText: (path: string, text: string) => void;
  now?: () => Date;
}

export interface Phase7RecordedCommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface Phase7CommandRecorderReport {
  schema: "split402.phase7_command_recorder.v1";
  ok: boolean;
  outputPath: string;
  commandCount: number;
  failedCommands: string[];
  written: boolean;
  nextActions: string[];
}

interface CommandSpec {
  command: string;
  file: string;
  args: readonly string[];
}

const safeLocalCommands: readonly CommandSpec[] = [
  {
    command: "git rev-parse HEAD",
    file: "git",
    args: ["rev-parse", "HEAD"],
  },
  {
    command: "git status --short --branch",
    file: "git",
    args: ["status", "--short", "--branch"],
  },
  {
    command: "corepack pnpm demo:mcp-gateway:smoke",
    file: "corepack",
    args: ["pnpm", "demo:mcp-gateway:smoke"],
  },
  {
    command: "corepack pnpm lint",
    file: "corepack",
    args: ["pnpm", "lint"],
  },
  {
    command: "corepack pnpm product:public-surface-check --brief",
    file: "corepack",
    args: ["pnpm", "product:public-surface-check", "--brief"],
  },
  {
    command: "corepack pnpm typecheck",
    file: "corepack",
    args: ["pnpm", "typecheck"],
  },
  {
    command: "corepack pnpm test",
    file: "corepack",
    args: ["pnpm", "test"],
  },
  {
    command: "corepack pnpm build",
    file: "corepack",
    args: ["pnpm", "build"],
  },
  {
    command: "corepack pnpm vectors:check",
    file: "corepack",
    args: ["pnpm", "vectors:check"],
  },
  {
    command: "corepack pnpm audit --audit-level high",
    file: "corepack",
    args: ["pnpm", "audit", "--audit-level", "high"],
  },
] as const;

const preflightCommand: CommandSpec = {
  command: "corepack pnpm product:launch-preflight --brief --workspace split402-launch-evidence",
  file: "corepack",
  args: [
    "pnpm",
    "product:launch-preflight",
    "--brief",
    "--workspace",
    "split402-launch-evidence",
  ],
};

export function recordPhase7LocalCommandEvidence(
  input: Phase7CommandRecorderInput,
): Phase7CommandRecorderReport {
  if (input.exists(input.outputPath) && input.force !== true) {
    return {
      schema: "split402.phase7_command_recorder.v1",
      ok: false,
      outputPath: input.outputPath,
      commandCount: 0,
      failedCommands: [],
      written: false,
      nextActions: [
        `Refusing to overwrite ${input.outputPath}; pass --force only after saving any real hosted transcript content.`,
      ],
    };
  }

  const commands = [
    ...(input.includePreflight === true ? [preflightCommand] : []),
    ...safeLocalCommands,
  ];
  const blocks: string[] = [
    "# Split402 Phase 7 command evidence transcript",
    "#",
    "# Generated by corepack pnpm phase7:staging:commands-record.",
    "# This records safe local validation commands only. Add hosted Docker, seed,",
    "# collection, paid-suite, manifest, assemble, and status command blocks from",
    "# the real hosted staging run before final Phase 7 approval.",
    `# generated_at: ${(input.now ?? (() => new Date()))().toISOString()}`,
    "",
  ];
  const failedCommands: string[] = [];

  for (const command of commands) {
    const result = input.runCommand(command.file, command.args);
    blocks.push(formatCommandBlock(command.command, result));
    if (result.exitCode !== 0) {
      failedCommands.push(command.command);
    }
  }

  const text = `${blocks.join("\n")}\n`;
  input.writeText(input.outputPath, text);

  return {
    schema: "split402.phase7_command_recorder.v1",
    ok: failedCommands.length === 0,
    outputPath: input.outputPath,
    commandCount: commands.length,
    failedCommands,
    written: true,
    nextActions: createNextActions(input.outputPath, failedCommands),
  };
}

function formatCommandBlock(
  command: string,
  result: Phase7RecordedCommandResult,
): string {
  return [
    `$ ${command}`,
    result.stdout.trimEnd(),
    result.stderr.trimEnd(),
    result.exitCode === 0 ? "" : `# exit_code: ${result.exitCode}`,
    "",
  ]
    .filter((line, index) => index === 0 || line.length > 0)
    .join("\n");
}

function createNextActions(
  outputPath: string,
  failedCommands: readonly string[],
): string[] {
  if (failedCommands.length > 0) {
    return [
      `Fix failed local commands: ${failedCommands.join(", ")}.`,
      `Rerun corepack pnpm phase7:staging:commands-record --force --output ${outputPath}.`,
    ];
  }

  return [
    `Append the hosted Docker, seed, collection, paid-suite, manifest, assemble, and status command outputs to ${outputPath}.`,
    `Run corepack pnpm phase7:staging:commands-status --brief ${outputPath} before assembling the Phase 7 proof.`,
  ];
}
