export interface Phase7CommandRecorderInput {
  outputPath: string;
  force?: boolean;
  includeHosted?: boolean;
  includePreflight?: boolean;
  evidenceEnvFile?: string;
  evidenceDirectory?: string;
  proofPath?: string;
  seedOutputPath?: string;
  exists: (path: string) => boolean;
  runCommand: (
    file: string,
    args: readonly string[],
  ) => Phase7RecordedCommandResult;
  sleep?: (milliseconds: number) => void;
  writeText: (path: string, text: string) => void;
  now?: () => Date;
}

export interface Phase7RecordedCommandResult {
  exitCode: number;
  stdout: string;
  stderr: string;
}

export interface Phase7CommandRecorderReport {
  schema: "split402.phase7_command_recorder.v1";
  ok: boolean;
  outputPath: string;
  commandCount: number;
  failedCommands: string[];
  written: boolean;
  nextActions: string[];
}

interface CommandSpec {
  command: string;
  file: string;
  args: readonly string[];
  outputPath?: string;
  retry?: {
    attempts: number;
    delayMs: number;
  };
}

const safeLocalCommands: readonly CommandSpec[] = [
  {
    command: "git rev-parse HEAD",
    file: "git",
    args: ["rev-parse", "HEAD"],
  },
  {
    command: "git status --short --branch",
    file: "git",
    args: ["status", "--short", "--branch"],
  },
  {
    command: "corepack pnpm demo:mcp-gateway:smoke",
    file: "corepack",
    args: ["pnpm", "demo:mcp-gateway:smoke"],
  },
  {
    command: "corepack pnpm lint",
    file: "corepack",
    args: ["pnpm", "lint"],
  },
  {
    command: "corepack pnpm product:public-surface-check --brief",
    file: "corepack",
    args: ["pnpm", "product:public-surface-check", "--brief"],
  },
  {
    command: "corepack pnpm typecheck",
    file: "corepack",
    args: ["pnpm", "typecheck"],
  },
  {
    command: "corepack pnpm test",
    file: "corepack",
    args: ["pnpm", "test"],
  },
  {
    command: "corepack pnpm build",
    file: "corepack",
    args: ["pnpm", "build"],
  },
  {
    command: "corepack pnpm vectors:check",
    file: "corepack",
    args: ["pnpm", "vectors:check"],
  },
  {
    command: "corepack pnpm audit --audit-level high",
    file: "corepack",
    args: ["pnpm", "audit", "--audit-level", "high"],
  },
] as const;

const preflightCommand: CommandSpec = {
  command: "corepack pnpm product:launch-preflight --brief --workspace split402-launch-evidence",
  file: "corepack",
  args: [
    "pnpm",
    "product:launch-preflight",
    "--brief",
    "--workspace",
    "split402-launch-evidence",
  ],
};

export function recordPhase7LocalCommandEvidence(
  input: Phase7CommandRecorderInput,
): Phase7CommandRecorderReport {
  if (input.exists(input.outputPath) && input.force !== true) {
    return {
      schema: "split402.phase7_command_recorder.v1",
      ok: false,
      outputPath: input.outputPath,
      commandCount: 0,
      failedCommands: [],
      written: false,
      nextActions: [
        `Refusing to overwrite ${input.outputPath}; pass --force only after saving any real hosted transcript content.`,
      ],
    };
  }

  const hostedCommands =
    input.includeHosted === true ? createHostedStagingCommands(input) : [];
  const commands = [
    ...(input.includePreflight === true || input.includeHosted === true
      ? [preflightCommand]
      : []),
    ...hostedCommands,
    ...safeLocalCommands,
  ];
  const blocks: string[] = [
    "# Split402 Phase 7 command evidence transcript",
    "#",
    "# Generated by corepack pnpm phase7:staging:commands-record.",
    input.includeHosted === true
      ? "# This includes hosted staging commands from this runtime."
      : "# This records safe local validation commands only. Add hosted Docker, seed,",
    ...(input.includeHosted === true
      ? [
          "# It must be run only after private hosted env values are filled.",
          "# Do not commit this transcript; keep it in the private evidence workspace.",
        ]
      : [
          "# collection, paid-suite, manifest, assemble, and status command blocks from",
          "# the real hosted staging run before final Phase 7 approval.",
        ]),
    `# generated_at: ${(input.now ?? (() => new Date()))().toISOString()}`,
    "",
  ];
  const failedCommands: string[] = [];

  for (const command of commands) {
    const result = runCommandWithRetry(input, command);
    if (
      command.outputPath !== undefined &&
      result.exitCode === 0 &&
      result.stdout.length > 0
    ) {
      input.writeText(command.outputPath, result.stdout);
    }
    blocks.push(formatCommandBlock(command.command, result));
    if (result.exitCode !== 0) {
      failedCommands.push(command.command);
    }
  }

  const text = `${blocks.join("\n")}\n`;
  input.writeText(input.outputPath, text);

  return {
    schema: "split402.phase7_command_recorder.v1",
    ok: failedCommands.length === 0,
    outputPath: input.outputPath,
    commandCount: commands.length,
    failedCommands,
    written: true,
    nextActions: createNextActions(input.outputPath, failedCommands),
  };
}

function runCommandWithRetry(
  input: Phase7CommandRecorderInput,
  command: CommandSpec,
): Phase7RecordedCommandResult {
  const attempts = command.retry?.attempts ?? 1;
  let result: Phase7RecordedCommandResult | undefined;

  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    result = input.runCommand(command.file, command.args);
    if (result.exitCode === 0 || attempt === attempts) {
      return result;
    }
    input.sleep?.(command.retry?.delayMs ?? 0);
  }

  return result ?? { exitCode: 1, stdout: "", stderr: "" };
}

function formatCommandBlock(
  command: string,
  result: Phase7RecordedCommandResult,
): string {
  return [
    `$ ${command}`,
    redactSensitiveCommandOutput(result.stdout).trimEnd(),
    redactSensitiveCommandOutput(result.stderr).trimEnd(),
    result.exitCode === 0 ? "" : `# exit_code: ${result.exitCode}`,
    "",
  ]
    .filter((line, index) => index === 0 || line.length > 0)
    .join("\n");
}

function createHostedStagingCommands(
  input: Pick<
    Phase7CommandRecorderInput,
    "evidenceDirectory" | "evidenceEnvFile" | "proofPath" | "seedOutputPath"
  >,
): CommandSpec[] {
  const evidenceDirectory =
    input.evidenceDirectory ?? "split402-launch-evidence/phase7-staging-evidence";
  const evidenceEnvFile =
    input.evidenceEnvFile ?? "split402-launch-evidence/phase7-staging.env";
  const proofPath =
    input.proofPath ?? "split402-launch-evidence/phase7-staging-proof.txt";
  const seedOutputPath =
    input.seedOutputPath ?? "split402-launch-evidence/phase7-seed.json";
  const evidenceEnvArgs = ["--evidence-env-file", evidenceEnvFile] as const;
  const artifact = (fileName: string): string =>
    `${evidenceDirectory}/${fileName}`;
  const withEvidenceEnv = (command: string): string =>
    `${command} --evidence-env-file ${evidenceEnvFile}`;

  return [
    {
      command: "corepack pnpm product:evidence:init --missing",
      file: "corepack",
      args: ["pnpm", "product:evidence:init", "--missing"],
    },
    {
      command: "corepack pnpm phase7:docker:doctor --brief",
      file: "corepack",
      args: ["pnpm", "phase7:docker:doctor", "--brief"],
    },
    {
      command: "corepack pnpm phase7:docker:doctor --brief --profile demo --profile workers",
      file: "corepack",
      args: [
        "pnpm",
        "phase7:docker:doctor",
        "--brief",
        "--profile",
        "demo",
        "--profile",
        "workers",
      ],
    },
    {
      command: "corepack pnpm phase7:docker:compose up --brief --profile demo --profile workers",
      file: "corepack",
      args: [
        "pnpm",
        "phase7:docker:compose",
        "up",
        "--brief",
        "--profile",
        "demo",
        "--profile",
        "workers",
      ],
    },
    {
      command: "corepack pnpm phase7:docker:health --brief --profile demo --profile workers",
      file: "corepack",
      args: [
        "pnpm",
        "phase7:docker:health",
        "--brief",
        "--profile",
        "demo",
        "--profile",
        "workers",
      ],
      retry: {
        attempts: 12,
        delayMs: 5000,
      },
    },
    {
      command: "corepack pnpm phase7:staging:seed",
      file: "corepack",
      args: ["pnpm", "phase7:staging:seed"],
      outputPath: seedOutputPath,
    },
    {
      command: `corepack pnpm phase7:staging:apply-seed-env --seed-output ${seedOutputPath}`,
      file: "corepack",
      args: [
        "pnpm",
        "phase7:staging:apply-seed-env",
        "--seed-output",
        seedOutputPath,
      ],
    },
    {
      command: `${withEvidenceEnv("corepack pnpm phase7:staging-proof")} ${proofPath}`,
      file: "corepack",
      args: ["pnpm", "phase7:staging-proof", ...evidenceEnvArgs, proofPath],
    },
    {
      command: withEvidenceEnv("corepack pnpm phase7:hosted:preflight"),
      file: "corepack",
      args: ["pnpm", "phase7:hosted:preflight", ...evidenceEnvArgs],
    },
    {
      command: `corepack pnpm demo:mcp-bundle ${artifact("mcp-bundle.json")}`,
      file: "corepack",
      args: ["pnpm", "demo:mcp-bundle", artifact("mcp-bundle.json")],
    },
    {
      command: `corepack pnpm demo:paid-suite ${artifact("paid-suite.log")}`,
      file: "corepack",
      args: ["pnpm", "demo:paid-suite", artifact("paid-suite.log")],
    },
    {
      command: [
        withEvidenceEnv("corepack pnpm phase7:staging:derive-receipt-verification"),
        artifact("paid-suite.log"),
        artifact("receipt-verification.json"),
      ].join(" "),
      file: "corepack",
      args: [
        "pnpm",
        "phase7:staging:derive-receipt-verification",
        ...evidenceEnvArgs,
        artifact("paid-suite.log"),
        artifact("receipt-verification.json"),
      ],
    },
    {
      command: withEvidenceEnv(
        "corepack pnpm phase7:staging:collect-mcp-gateway",
      ),
      file: "corepack",
      args: ["pnpm", "phase7:staging:collect-mcp-gateway", ...evidenceEnvArgs],
    },
    {
      command: withEvidenceEnv("corepack pnpm phase7:staging:collect-reads"),
      file: "corepack",
      args: ["pnpm", "phase7:staging:collect-reads", ...evidenceEnvArgs],
    },
    {
      command: [
        "corepack pnpm phase7:staging:manifest",
        proofPath,
        artifact("artifact-manifest.json"),
      ].join(" "),
      file: "corepack",
      args: [
        "pnpm",
        "phase7:staging:manifest",
        proofPath,
        artifact("artifact-manifest.json"),
      ],
    },
    {
      command: `${withEvidenceEnv("corepack pnpm phase7:staging:assemble")} ${proofPath}`,
      file: "corepack",
      args: ["pnpm", "phase7:staging:assemble", ...evidenceEnvArgs, proofPath],
    },
    {
      command: `corepack pnpm phase7:staging:status --brief ${proofPath}`,
      file: "corepack",
      args: ["pnpm", "phase7:staging:status", "--brief", proofPath],
    },
  ];
}

function createNextActions(
  outputPath: string,
  failedCommands: readonly string[],
): string[] {
  if (failedCommands.length > 0) {
    return [
      `Fix failed local commands: ${failedCommands.join(", ")}.`,
      `Rerun corepack pnpm phase7:staging:commands-record --force --output ${outputPath}.`,
    ];
  }

  return [
    `Append any missing hosted Docker, seed, collection, paid-suite, manifest, assemble, and status command outputs to ${outputPath}.`,
    `Run corepack pnpm phase7:staging:commands-status --brief ${outputPath} before assembling the Phase 7 proof.`,
  ];
}

function redactSensitiveCommandOutput(text: string): string {
  return text
    .replace(
      /("(?:[^"]*(?:TOKEN|PRIVATE_KEY|SEED|SECRET)[^"]*)"\s*:\s*")([^"]+)(")/giu,
      "$1[redacted]$3",
    )
    .replace(
      /^((?:[A-Z0-9_]*(?:TOKEN|PRIVATE_KEY|SEED|SECRET)[A-Z0-9_]*)=).+$/gimu,
      "$1[redacted]",
    );
}
